### ISSUE TITLE
snappy-start-all.sh on single machine

### ISSUE THREAD

**Issue by Chen-Huanyi** [barryvdh/laravel-snappy#333]
I just install snappy and want to run it on a single virtual machine. However, it gives:

```
huanyi@snappy1:~/snappydata-1.0.2.1-bin$ ./sbin/snappy-start-all.sh
Logs generated in /home/huanyi/snappydata-1.0.2.1-bin/work/localhost-locator-1/snappylocator.log
SnappyData Locator pid: 10573 status: running
  Distributed system now has 1 members.
  Started Thrift locator (Compact Protocol) on: localhost/127.0.0.1[1527]
Exception in thread "main" java.io.IOException: No available status. Either status file ".snappyserver.stat" is not readable or reading the status file timed out.
	at com.gemstone.gemfire.internal.shared.LauncherBase.waitForRunning(LauncherBase.java:456)
	at io.snappydata.tools.QuickLauncher.start(QuickLauncher.java:248)
	at io.snappydata.tools.QuickLauncher.main(QuickLauncher.java:73)
Exception in thread "main" java.io.IOException: No available status. Either status file ".snappyleader.stat" is not readable or reading the status file timed out.
	at com.gemstone.gemfire.internal.shared.LauncherBase.waitForRunning(LauncherBase.java:456)
	at io.snappydata.tools.QuickLauncher.start(QuickLauncher.java:248)
	at io.snappydata.tools.QuickLauncher.main(QuickLauncher.java:73)
```

I was wondering what is the issue here?

**Comment by Chen-Huanyi** [comment]
Sorry post it to the wrong place ...
